### ISSUE TITLE
No polyline is drawn

### ISSUE THREAD

**Issue by ArjunBhilare** [tintinscorpion/Dual-color-Polyline-Animation#13]
mMap.addPolyline(points); draws polyline but MapAnimator.getInstance().animateRoute(googleMap, points); does NOT draw. Pleas help

**Comment by tintinscorpion** [comment]
@ArjunBhilare Its fixed now in the latest version 1.1.. Hopefully you can test and provide feedback,

**Comment by lUjek-Sh** [comment]
> mMap.addPolyline(points); draws polyline but MapAnimator.getInstance().animateRoute(googleMap, points); does NOT draw. Pleas help

@ArjunBhilare check this https://github.com/tintinscorpion/Dual-color-Polyline-Animation/issues/14#issuecomment-845470814

**Comment by tintinscorpion** [comment]
I have updated in readme what to do if you are enabling the proguard or R8 and tested to confirm it and hence closing the issue.
