### ISSUE TITLE
Route is not drawn

### ISSUE THREAD

**Issue by lUjek-Sh** [tintinscorpion/Dual-color-Polyline-Animation#14]
**Screenshots**
https://drive.google.com/file/d/1X6tSj6KZSgPH2bPijRY8wKbZG_7iza5I/view?usp=sharing - Video Here

**Smartphone (please complete the following information):**
 - Device: New Samsung: Galaxy S20, Galaxy A50 and more
 - OS: Android 11

**Additional context**
Route is not drawn only New Samsung. Emulator wor good.

**Comment by tintinscorpion** [comment]
@lUjek-Sh Please update the build and check. Provide feedback so that I can close.

**Comment by lUjek-Sh** [comment]
Поскольку ошибка была только тогда, когда
minifyEnabled true
shrinkResources true,
я поясню , как я решил эту проблему.
Я добавил библиотеку в исключение в файле proguard-rules.pro

**Comment by lUjek-Sh** [comment]
but if you need to check version 1.1. Then I will check and give feedback.

**Comment by lUjek-Sh** [comment]
> Please update the build and check. Provide feedback so that I can close.

Updated version to 1.1. And the route still does not resize until I added
-keep class com.logicbeanzs. ** {*; }
in proguard-rules.pro file

**Comment by tintinscorpion** [comment]
@lUjek-Sh So you mean when you are using R8 or proguard at that time the class gets obfuscated?

**Comment by lUjek-Sh** [comment]
> @ lUjek-Sh Так вы имеете в виду, когда вы используете R8 или proguard в это время, класс запутывается?

Right. When not using R8 it works fine.

**Comment by tintinscorpion** [comment]
@lUjek-Sh Thanks for testing it and I have updated the Readme accordingly and hence closing the issue.
