### ISSUE TITLE
when polyline is geodesic, it doesn't show the trail animation

### ISSUE THREAD

**Issue by aurangzaibumer777** [tintinscorpion/Dual-color-Polyline-Animation#4]
is this possible to achieve the trail animation when polylines are set to geodesic

**Comment by tintinscorpion** [comment]
Yes , I checked that polyline animation is showing even in geodesic. I checked geodesic as a plain line between two points and its happening in that scenario but for arc I havenot tested, I will test and report it.

**Comment by aurangzaibumer777** [comment]
yes, if you set geoDesic(True) in that case, there are two different polylines being drawn, one is with geoDesic and another one is without geoDesic, the one that sends a Route Evaluator in Animation object that are only two points.

**Comment by aurangzaibumer777** [comment]
So this is the case
if you create a simple polyline with the Geo Desic ON
val simplePolyline = PolylineOptions().add(mapHomeViewModel.departure).add(mapHomeViewModel.arrival).geodesic(true).width(8f).color(resources.getColor(R.color.New_Vista_RED))
        googleMap?.addPolyline(simplePolyline)


now if i want to animate this polyline with a trail animation (not pulse), just a single trail animation with single color and that doesn't repeat itself after drawn. how can i achieve this?

the polyline that animates will be as same as the polyline created by google with the geoDesic ON

thanks

**Comment by tintinscorpion** [comment]
The scenario you are saying can be acheived if you pass a transparent color to the secondary Line color. 
MapAnimator.getInstance().setPrimaryLineColor(color); // pass primary color
MapAnimator.getInstance().setSecondaryLineColor(color); // pass transparent color
 
If you go through the library file you will get these methods.
 public void setPercentCompletion(@IntegerRes int time) {
        PERCENT_COMPLETION = time;
    }

    public void setColorFillCompletion(@IntegerRes int time) {
        COLOR_FILL_ANIMATION = time;
    }

    public void setPrimaryLineCompletion(@IntegerRes int time) {
        FOREGROUND_TIME = time;
    }

    public void setDelayTime(@IntegerRes int time) {
        DELAY_TIME = time;
    }

set your custom values and I guess you can achieve that animation. But this doesnot take arc polyline. It will be a single line polyline with the desired animation.

**Comment by aurangzaibumer777** [comment]
yes that is what i was saying that if you set google polyline to geoDesic state, it won't animate like a trail animation does.

**Comment by aurangzaibumer777** [comment]
i have to show trail animation when polyline is explicitly set to geoDesic state.

**Comment by aurangzaibumer777** [comment]
i was looking for some algorithm that gives me geoDesic points after i give him my first and last coordinates (departure and destination latLngs) but haven't figured it out, even the google map doesn't give us the geoDesic latlng after we give him the points.

**Comment by tintinscorpion** [comment]
Till What I have understood is Are you referring something like this?
https://raw.githubusercontent.com/akexorcist/Android-GoogleDirectionLibrary/master/image/google-direction-library_02.jpg

**Comment by aurangzaibumer777** [comment]
https://alastaira.files.wordpress.com/2011/06/image41.png

the blue line is the polyline, i want to have a trail animation on that, not the pulse effect.

**Comment by tintinscorpion** [comment]
Ok so now I got your point. Ok I will add that feature in this library.. Give me two days.

**Comment by aurangzaibumer777** [comment]
> Ok so now I got your point. Ok I will add that feature in this library.. Give me two days.

have you achieved it?

**Comment by delmeluck** [comment]
MapAnimator.getInstance().animateRoute(mMap, polylineList); generates this error in my emulator any help ?


android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@57da9ab is not valid; is your activity running?
        at android.view.ViewRootImpl.setView(ViewRootImpl.java:679)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:342)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
        at android.widget.Toast$TN.handleShow(Toast.java:467)
        at android.widget.Toast$TN$2.handleMessage(Toast.java:350)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6125)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
